name: image-builder

permissions:
  contents: read

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
    paths:
      - "docker/**"
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push image to registry'
        type: boolean
        default: false

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: build-sglang-plugin-fl-cuda-ci
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'sglang-plugin-fl'
            tag: 'latest-cuda-ci'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=harbor.baai.ac.cn/flagbase/flagbase-nvidia
              BASE_IMAGE_VERSION=latest

    name: ${{ matrix.job_name }}
    uses: flagos-ai/build-infra/.github/workflows/imagebuild.yml@main
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagos-dev'
      no-cache: ${{ matrix.no-cache }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
