name: image-builder

permissions:
  contents: read

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
    paths:
      - "container/**"
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push image to registry'
        type: boolean
        default: false

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: build-sglang-plugin-fl-cuda-ci
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile'
            image_name: 'sglang-plugin-fl'
            tag: 'latest-cuda-ci'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              CUDA_VERSION=12.8.1
              UBUNTU_VERSION=22.04

          - job_name: build-sglang-plugin-fl-ascend-ci
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'ascend/containerfile'
            image_name: 'sglang-plugin-fl'
            tag: 'latest-ascend-ci'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              CANN_VERSION=8.5.1
              CANN_CHIP=a3
              UBUNTU_VERSION=22.04
              PYTHON_VERSION=3.11

          - job_name: build-sglang-plugin-fl-musa-ci
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'musa/containerfile'
            image_name: 'sglang-plugin-fl'
            tag: 'latest-musa-ci'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              BASE_IMAGE=mthreads/musa
              BASE_IMAGE_VERSION=rc4.3.6-devel-ubuntu22.04

    name: ${{ matrix.job_name }}
    uses: flagos-ai/build-infra/.github/workflows/imagebuild.yml@main
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagos-dev'
      no-cache: ${{ matrix.no-cache }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
